[project]
name = "my_project"
version = "0.1.0"
description = "Un projet Python structur√©"
authors = [{name = "Ton Nom"}]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
